### ISSUE TITLE
stanExports Errors

### ISSUE THREAD

**Issue by joshua-zh** [cdriveraus/bigIRT#2]
```
remotes::install_github('cdriveraus/bigIRT', INSTALL_opts = "--no-multiarch", dependencies = c("Depends", "Imports"))
Downloading GitHub repo cdriveraus/bigIRT@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/sj/jdgnsm9n14vgsjctfrk5x2_80000gn/T/RtmpjRu0CI/remotes24b141391118/cdriveraus-bigIRT-e636cb9/DESCRIPTION’ ...
─  preparing ‘bigIRT’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘bigIRT_0.1.6.tar.gz’
   
* installing *source* package ‘bigIRT’ ...
** using staged installation
** libs
using C++ compiler: ‘Homebrew clang version 18.1.6’
using C++17
using SDK: ‘MacOSX14.4.sdk’


clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include' -I/opt/homebrew/include    -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o


clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include' -I/opt/homebrew/include    -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS   -fPIC  -falign-functions=64 -Wall -g -O2  -c stanExports_irt.cc -o stanExports_irt.o


In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:26:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseCore:61:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseCore/TriangularSolver.h:273:13: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  273 |       Index count = 0;
      |             ^
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseLU:35:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:78:9: warning: variable 'nsuper_et_post' set but not used [-Wunused-but-set-variable]
   78 |   Index nsuper_et_post = 0; // Number of relaxed snodes in postordered etree 
      |         ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:79:9: warning: variable 'nsuper_et' set but not used [-Wunused-but-set-variable]
   79 |   Index nsuper_et = 0; // Number of relaxed snodes in the original etree 
      |         ^
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/IterativeSolvers:46:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/IterativeSolvers/IDRS.h:72:10: warning: variable 'replacements' set but not used [-Wunused-but-set-variable]
   72 |                         Index replacements = 0;
      |                               ^
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include' -I/opt/homebrew/include    -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS   -fPIC  -falign-functions=64 -Wall -g -O2  -c stanExports_irtmml.cc -o stanExports_irtmml.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:37:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:45:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MarketIO.h:246:7: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  246 |   int count = 0;
      |       ^
5 warnings generated.
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:26:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseCore:61:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseCore/TriangularSolver.h:273:13: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  273 |       Index count = 0;
      |             ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseLU:35:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:78:9: warning: variable 'nsuper_et_post' set but not used [-Wunused-but-set-variable]
   78 |   Index nsuper_et_post = 0; // Number of relaxed snodes in postordered etree 
      |         ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:79:9: warning: variable 'nsuper_et' set but not used [-Wunused-but-set-variable]
   79 |   Index nsuper_et = 0; // Number of relaxed snodes in the original etree 
      |         ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:47:31: warning: 'rstan::io::r_cout_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   47 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:70:31: warning: 'rstan::io::r_cerr_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   70 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/IterativeSolvers:46:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/IterativeSolvers/IDRS.h:72:10: warning: variable 'replacements' set but not used [-Wunused-but-set-variable]
   72 |                         Index replacements = 0;
      |                               ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:37:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:45:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MarketIO.h:246:7: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  246 |   int count = 0;
      |       ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:26:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseCore:61:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseCore/TriangularSolver.h:273:13: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  273 |       Index count = 0;
      |             ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseLU:35:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:78:9: warning: variable 'nsuper_et_post' set but not used [-Wunused-but-set-variable]
   78 |   Index nsuper_et_post = 0; // Number of relaxed snodes in postordered etree 
      |         ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:79:9: warning: variable 'nsuper_et' set but not used [-Wunused-but-set-variable]
   79 |   Index nsuper_et = 0; // Number of relaxed snodes in the original etree 
      |         ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:47:31: warning: 'rstan::io::r_cout_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   47 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:70:31: warning: 'rstan::io::r_cerr_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   70 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/IterativeSolvers:46:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/IterativeSolvers/IDRS.h:72:10: warning: variable 'replacements' set but not used [-Wunused-but-set-variable]
   72 |                         Index replacements = 0;
      |                               ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:37:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:45:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MarketIO.h:246:7: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  246 |   int count = 0;
      |       ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:35:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/binomial_coefficient_log.hpp:13:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/partials_propagator.hpp:8:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:57:1: warning: 'ops_partials_edge' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   57 | struct ops_partials_edge<ViewElt, Op, require_st_arithmetic<Op>> {
      | ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:45:1: note: did you mean struct here?
   45 | class ops_partials_edge;
      | ^~~~~
      | struct
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:35:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/binomial_coefficient_log.hpp:13:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/partials_propagator.hpp:8:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:57:1: warning: 'ops_partials_edge' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   57 | struct ops_partials_edge<ViewElt, Op, require_st_arithmetic<Op>> {
      | ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:45:1: note: did you mean struct here?
   45 | class ops_partials_edge;
      | ^~~~~
      | struct
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:1252:9: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
 1252 |     int ret = stan::services::error_codes::CONFIG;
      |         ^
In file included from stanExports_irt.cc:5:
./stanExports_irt.h:638:10: error: expected member name or ';' after declaration specifiers
  638 |   double BSD;
      |   ~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/param.h:72:17: note: expanded from macro 'BSD'
   72 | #define BSD     199506          /* System version (year & month). */
      |                 ^
In file included from stanExports_irt.cc:5:
./stanExports_irt.h:1437:11: error: expression is not assignable
 1437 |       BSD = std::numeric_limits<double>::quiet_NaN();
      |       ~~~ ^
./stanExports_irt.h:1439:11: error: expression is not assignable
 1439 |       BSD = context__.vals_r("BSD")[(1 - 1)];
      |       ~~~ ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:1252:9: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
 1252 |     int ret = stan::services::error_codes::CONFIG;
      |         ^
In file included from stanExports_irtmml.cc:5:
./stanExports_irtmml.h:577:10: error: expected member name or ';' after declaration specifiers
  577 |   double BSD;
      |   ~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/param.h:72:17: note: expanded from macro 'BSD'
   72 | #define BSD     199506          /* System version (year & month). */
      |                 ^
In file included from stanExports_irtmml.cc:5:
./stanExports_irtmml.h:1374:11: error: expression is not assignable
 1374 |       BSD = std::numeric_limits<double>::quiet_NaN();
      |       ~~~ ^
./stanExports_irtmml.h:1376:11: error: expression is not assignable
 1376 |       BSD = context__.vals_r("BSD")[(1 - 1)];
      |       ~~~ ^
./stanExports_irt.h:2747:20: warning: unused variable 'jacobian__' [-Wunused-variable]
 2747 |     constexpr bool jacobian__ = false;
      |                    ^~~~~~~~~~
./stanExports_irt.h:4036:11: warning: variable 'pos__' set but not used [-Wunused-but-set-variable]
 4036 |       int pos__ = std::numeric_limits<int>::min();
      |           ^
./stanExports_irtmml.h:2430:20: warning: unused variable 'jacobian__' [-Wunused-variable]
 2430 |     constexpr bool jacobian__ = false;
      |                    ^~~~~~~~~~
./stanExports_irtmml.h:3474:11: warning: variable 'pos__' set but not used [-Wunused-but-set-variable]
 3474 |       int pos__ = std::numeric_limits<int>::min();
      |           ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:46:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/choose.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/binomial.hpp:15:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/beta.hpp:1721:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:29:15: warning: unused variable 'x_extrema' [-Wunused-variable]
   29 |       const T x_extrema = 1 / (1 + a);
      |               ^~~~~~~~~
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:304:7: note: in instantiation of member function 'boost::math::detail::temme_root_finder<double>::temme_root_finder' requested here
  304 |       temme_root_finder<T>(-lu, alpha), x, lower, upper, policies::digits<T, Policy>() / 2);
      |       ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:615:20: note: in instantiation of function template specialization 'boost::math::detail::temme_method_2_ibeta_inverse<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  615 |                x = temme_method_2_ibeta_inverse(a, b, p, r, theta, pol);
      |                    ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:992:17: note: in instantiation of function template specialization 'boost::math::detail::ibeta_inv_imp<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  992 |    rx = detail::ibeta_inv_imp(
      |                 ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:1023:11: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
 1023 |    return ibeta_inv(a, b, p, static_cast<result_type*>(nullptr), pol);
      |           ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/inv_inc_beta.hpp:32:23: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
   32 |   return boost::math::ibeta_inv(a, b, p, boost_policy_t<>());
      |                       ^
In file included from stanExports_irtmml.cc:5:
In file included from ./stanExports_irtmml.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:46:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/choose.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/binomial.hpp:15:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/beta.hpp:1721:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:29:15: warning: unused variable 'x_extrema' [-Wunused-variable]
   29 |       const T x_extrema = 1 / (1 + a);
      |               ^~~~~~~~~
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:304:7: note: in instantiation of member function 'boost::math::detail::temme_root_finder<double>::temme_root_finder' requested here
  304 |       temme_root_finder<T>(-lu, alpha), x, lower, upper, policies::digits<T, Policy>() / 2);
      |       ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:615:20: note: in instantiation of function template specialization 'boost::math::detail::temme_method_2_ibeta_inverse<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  615 |                x = temme_method_2_ibeta_inverse(a, b, p, r, theta, pol);
      |                    ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:992:17: note: in instantiation of function template specialization 'boost::math::detail::ibeta_inv_imp<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  992 |    rx = detail::ibeta_inv_imp(
      |                 ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:1023:11: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
 1023 |    return ibeta_inv(a, b, p, static_cast<result_type*>(nullptr), pol);
      |           ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/inv_inc_beta.hpp:32:23: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
   32 |   return boost::math::ibeta_inv(a, b, p, boost_policy_t<>());
      |                       ^
12 warnings and 3 errors generated.
make: *** [stanExports_irtmml.o] Error 1
make: *** Waiting for unfinished jobs....
12 warnings and 3 errors generated.
make: *** [stanExports_irt.o] Error 1
ERROR: compilation failed for package ‘bigIRT’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/bigIRT’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/sj/jdgnsm9n14vgsjctfrk5x2_80000gn/T//RtmpjRu0CI/file24b153f9ee0a/bigIRT_0.1.6.tar.gz’ had non-zero exit status
```

**Comment by cdriveraus** [comment]
There have been some difficulties compiling stan models on mac from time to time, I believe it should have all been fixed though -- can you try updating all your R packages, restarting R / rstudio, and reinstalling? I've pushed a new version where less compilation is required though I doubt that will change things...

**Comment by joshua-zh** [comment]
Sorry, the same errors still remained. 
Thanks for your reply. 

```
remotes::install_github('cdriveraus/bigIRT', INSTALL_opts = "--no-multiarch", dependencies = c("Depends", "Imports"))
Downloading GitHub repo cdriveraus/bigIRT@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/sj/jdgnsm9n14vgsjctfrk5x2_80000gn/T/RtmpSKu0qu/remotes58032e32b87c/cdriveraus-bigIRT-644a66d/DESCRIPTION’ ...
─  preparing ‘bigIRT’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘bigIRT_0.1.7.tar.gz’
   
* installing *source* package ‘bigIRT’ ...
** using staged installation
** libs
using C++ compiler: ‘Homebrew clang version 18.1.6’
using C++17
using SDK: ‘MacOSX14.4.sdk’


clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include' -I/opt/R/arm64/include    -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o


clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"../inst/include" -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -DUSE_STANC3 -D_HAS_AUTO_PTR_ETC=0 -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include' -I/opt/R/arm64/include    -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppParallel/include' -D_REENTRANT -DSTAN_THREADS   -fPIC  -falign-functions=64 -Wall -g -O2  -c stanExports_irt.cc -o stanExports_irt.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:26:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseCore:61:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseCore/TriangularSolver.h:273:13: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  273 |       Index count = 0;
      |             ^
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseLU:35:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:78:9: warning: variable 'nsuper_et_post' set but not used [-Wunused-but-set-variable]
   78 |   Index nsuper_et_post = 0; // Number of relaxed snodes in postordered etree 
      |         ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:79:9: warning: variable 'nsuper_et' set but not used [-Wunused-but-set-variable]
   79 |   Index nsuper_et = 0; // Number of relaxed snodes in the original etree 
      |         ^
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/IterativeSolvers:46:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/IterativeSolvers/IDRS.h:72:10: warning: variable 'replacements' set but not used [-Wunused-but-set-variable]
   72 |                         Index replacements = 0;
      |                               ^
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:37:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:45:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MarketIO.h:246:7: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  246 |   int count = 0;
      |       ^
5 warnings generated.
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:26:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseCore:61:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseCore/TriangularSolver.h:273:13: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  273 |       Index count = 0;
      |             ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/Sparse:29:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/SparseLU:35:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:78:9: warning: variable 'nsuper_et_post' set but not used [-Wunused-but-set-variable]
   78 |   Index nsuper_et_post = 0; // Number of relaxed snodes in postordered etree 
      |         ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h:79:9: warning: variable 'nsuper_et' set but not used [-Wunused-but-set-variable]
   79 |   Index nsuper_et = 0; // Number of relaxed snodes in the original etree 
      |         ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:47:31: warning: 'rstan::io::r_cout_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   47 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:21:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/io/r_ostream.hpp:70:31: warning: 'rstan::io::r_cerr_streambuf::xsputn' hides overloaded virtual function [-Woverloaded-virtual]
   70 |       virtual std::streamsize xsputn(const char_type* s, int n) {
      |                               ^
/opt/homebrew/opt/llvm/bin/../include/c++/v1/streambuf:276:22: note: hidden overloaded virtual function 'std::basic_streambuf<char>::xsputn' declared here: type mismatch at 2nd parameter ('streamsize' (aka 'long') vs 'int')
  276 |   virtual streamsize xsputn(const char_type* __s, streamsize __n);
      |                      ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/IterativeSolvers:46:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/IterativeSolvers/IDRS.h:72:10: warning: variable 'replacements' set but not used [-Wunused-but-set-variable]
   72 |                         Index replacements = 0;
      |                               ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:31:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:37:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:45:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MarketIO.h:246:7: warning: variable 'count' set but not used [-Wunused-but-set-variable]
  246 |   int count = 0;
      |       ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:35:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/binomial_coefficient_log.hpp:13:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/partials_propagator.hpp:8:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:57:1: warning: 'ops_partials_edge' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
   57 | struct ops_partials_edge<ViewElt, Op, require_st_arithmetic<Op>> {
      | ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/functor/operands_and_partials.hpp:45:1: note: did you mean struct here?
   45 | class ops_partials_edge;
      | ^~~~~
      | struct
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:1252:9: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
 1252 |     int ret = stan::services::error_codes::CONFIG;
      |         ^
In file included from stanExports_irt.cc:5:
./stanExports_irt.h:638:10: error: expected member name or ';' after declaration specifiers
  638 |   double BSD;
      |   ~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/param.h:72:17: note: expanded from macro 'BSD'
   72 | #define BSD     199506          /* System version (year & month). */
      |                 ^
In file included from stanExports_irt.cc:5:
./stanExports_irt.h:1437:11: error: expression is not assignable
 1437 |       BSD = std::numeric_limits<double>::quiet_NaN();
      |       ~~~ ^
./stanExports_irt.h:1439:11: error: expression is not assignable
 1439 |       BSD = context__.vals_r("BSD")[(1 - 1)];
      |       ~~~ ^
./stanExports_irt.h:2747:20: warning: unused variable 'jacobian__' [-Wunused-variable]
 2747 |     constexpr bool jacobian__ = false;
      |                    ^~~~~~~~~~
./stanExports_irt.h:4036:11: warning: variable 'pos__' set but not used [-Wunused-but-set-variable]
 4036 |       int pos__ = std::numeric_limits<int>::min();
      |           ^
In file included from stanExports_irt.cc:5:
In file included from ./stanExports_irt.h:23:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rstan/include/rstan/stan_fit.hpp:43:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/src/stan/io/dump.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim.hpp:14:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun.hpp:46:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/choose.hpp:7:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/binomial.hpp:15:
In file included from /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/beta.hpp:1721:
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:29:15: warning: unused variable 'x_extrema' [-Wunused-variable]
   29 |       const T x_extrema = 1 / (1 + a);
      |               ^~~~~~~~~
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:304:7: note: in instantiation of member function 'boost::math::detail::temme_root_finder<double>::temme_root_finder' requested here
  304 |       temme_root_finder<T>(-lu, alpha), x, lower, upper, policies::digits<T, Policy>() / 2);
      |       ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:615:20: note: in instantiation of function template specialization 'boost::math::detail::temme_method_2_ibeta_inverse<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  615 |                x = temme_method_2_ibeta_inverse(a, b, p, r, theta, pol);
      |                    ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:992:17: note: in instantiation of function template specialization 'boost::math::detail::ibeta_inv_imp<double, boost::math::policies::policy<boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>>>' requested here
  992 |    rx = detail::ibeta_inv_imp(
      |                 ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/BH/include/boost/math/special_functions/detail/ibeta_inverse.hpp:1023:11: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
 1023 |    return ibeta_inv(a, b, p, static_cast<result_type*>(nullptr), pol);
      |           ^
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/StanHeaders/include/stan/math/prim/fun/inv_inc_beta.hpp:32:23: note: in instantiation of function template specialization 'boost::math::ibeta_inv<double, double, double, boost::math::policies::policy<boost::math::policies::overflow_error<>, boost::math::policies::pole_error<boost::math::policies::errno_on_error>, boost::math::policies::promote_double<false>, boost::math::policies::digits2<>>>' requested here
   32 |   return boost::math::ibeta_inv(a, b, p, boost_policy_t<>());
      |                       ^
12 warnings and 3 errors generated.
make: *** [stanExports_irt.o] Error 1
ERROR: compilation failed for package ‘bigIRT’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/bigIRT’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/sj/jdgnsm9n14vgsjctfrk5x2_80000gn/T//RtmpSKu0qu/file58036e750d64/bigIRT_0.1.7.tar.gz’ had non-zero exit status
```

**Comment by cdriveraus** [comment]
Ok. I've posted on the stan forum to see if there's any help available. https://discourse.mc-stan.org/t/mac-compilation-error/35282

**Comment by cdriveraus** [comment]
Ok, problem is fixed thanks to some help.
